name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node_version: [8, 10, 11]

    name: CI
    runs-on: ubuntu-latest
    steps:

    - name: Checkout scm
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}.x
        cache: npm

    - name: Run test
      run: |
        npm ci
        npm run test
        npm run lint
